# URL cuando estás en Docker (usa nombre del servicio)
auth.url=http://auth-service:8080/api/auth/validate

# Circuit Breaker (puedes repetir o dejar igual)
resilience4j.circuitbreaker.instances.authService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.authService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.authService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.authService.permittedNumberOfCallsInHalfOpenState=3