spring.application.name=pacientes

server.port=8082

# URL cuando estás en Docker (usa nombre del servicio)
auth.url=http://auth-service:8081/api/auth/validate

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/cuidado_seguro_pacientes?createDatabaseIfNotExist=true}

# Usuario MySQL
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}

# Contraseña MySQL
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cuidadoseguropacientes}

# Circuit Breaker (puedes repetir o dejar igual)
resilience4j.circuitbreaker.instances.authService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.authService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.authService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.authService.permittedNumberOfCallsInHalfOpenState=3

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIÓN JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Linea de código para poder detectar los errores con colores diferentes
spring.output.ansi.enabled=always