# Nombre del microservicio
spring.application.name=pacientes

# Puerto del microservicio
server.port=8082

# URL del microservicio de autenticación
auth.url=http://localhost:9999/api/auth/validate

# Configuración Circuit Breaker
resilience4j.circuitbreaker.instances.authService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.authService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.authService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.authService.permittedNumberOfCallsInHalfOpenState=2