spring.application.name=pacientes

server.port=8082

auth.url=http://localhost:9999/api/auth/validate

# Circuit Breaker configuración
resilience4j.circuitbreaker.instances.authService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.authService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.authService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.authService.permittedNumberOfCallsInHalfOpenState=3